# Generated by Django 3.2.5 on 2021-11-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
