# Generated by Django 3.2.8 on 2021-11-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mob03_library', '0002_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mob03_library.state'),
            preserve_default=False,
        ),
    ]
