# Generated by Django 3.2.5 on 2021-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('height', models.FloatField(verbose_name='')),
                ('weight', models.FloatField(verbose_name='')),
                ('image_front', models.CharField(max_length=50, verbose_name='')),
                ('image_back', models.CharField(max_length=50, verbose_name='')),
                ('types', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
