# Generated by Django 3.2.8 on 2021-11-10 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='tweet',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
