# Generated by Django 2.2.6 on 2021-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlwebservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
