# Generated by Django 4.0 on 2021-12-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newapplication',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='user',
        ),
    ]
