# Generated by Django 3.2.8 on 2022-01-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=200)),
                ('capacity', models.FloatField()),
                ('quality', models.FloatField()),
                ('timeliness', models.FloatField()),
                ('capacity_ave', models.FloatField()),
                ('quality_ave', models.FloatField()),
                ('timeliness_ave', models.FloatField()),
                ('capacity_stdev', models.FloatField()),
                ('quality_stdev', models.FloatField()),
                ('timeliness_stdev', models.FloatField()),
                ('item_id', models.CharField(max_length=200)),
                ('item_value', models.FloatField()),
            ],
        ),
    ]
