# Generated by Django 3.2.8 on 2022-01-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='item_id',
            new_name='supplierid',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='capacity_ave',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='capacity_stdev',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='item_value',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quality_ave',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quality_stdev',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='timeliness',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='timeliness_ave',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='timeliness_stdev',
        ),
    ]
