# Generated by Django 3.2.8 on 2022-01-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0002_auto_20220110_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='capacity_ave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='capacity_stdev',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_ave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_stdev',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='timeliness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='timeliness_ave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='timeliness_stdev',
            field=models.FloatField(default=0),
        ),
    ]
