# Generated by Django 3.2.8 on 2022-01-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0003_auto_20220110_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(max_length=200)),
                ('m_capacity', models.FloatField(default=0)),
                ('m_quality', models.FloatField(default=0)),
                ('m_timeliness', models.FloatField(default=0)),
                ('m_capacity_ave', models.FloatField(default=0)),
                ('m_quality_ave', models.FloatField(default=0)),
                ('m_timeliness_ave', models.FloatField(default=0)),
                ('m_capacity_stdev', models.FloatField(default=0)),
                ('m_quality_stdev', models.IntegerField(default=0)),
                ('m_timeliness_stdev', models.FloatField(default=0)),
                ('agg_sys_id', models.CharField(default=0, max_length=200)),
                ('agg_sys_value', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuechain.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('c_capacity', models.FloatField(default=0)),
                ('c_quality', models.FloatField(default=0)),
                ('c_timeliness', models.FloatField(default=0)),
                ('c_capacity_ave', models.FloatField(default=0)),
                ('c_quality_ave', models.FloatField(default=0)),
                ('c_timeliness_ave', models.FloatField(default=0)),
                ('c_capacity_stdev', models.FloatField(default=0)),
                ('c_quality_stdev', models.IntegerField(default=0)),
                ('c_timeliness_stdev', models.FloatField(default=0)),
                ('c_sys_id', models.CharField(default=0, max_length=200)),
                ('c_sys_value', models.FloatField(default=0)),
                ('split_shipments', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuechain.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuechain.supplier')),
            ],
        ),
    ]
