# Generated by Django 3.2.8 on 2022-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0004_customer_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_quality_stdev',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='m_quality_stdev',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quality_stdev',
            field=models.FloatField(default=0),
        ),
    ]
