# Generated by Django 3.2.8 on 2022-01-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0006_remove_customer_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_capacity_stdev',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_quality_stdev',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_timeliness_stdev',
        ),
    ]
