# Generated by Django 3.2.8 on 2022-01-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuechain', '0007_auto_20220118_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='m_capacity_stdev',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='m_quality_stdev',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='m_timeliness_stdev',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='capacity_stdev',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='quality_stdev',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='timeliness_stdev',
        ),
    ]
