# Generated by Django 3.2.8 on 2022-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
