# Generated by Django 3.2.8 on 2022-01-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='public',
        ),
    ]
