# Generated by Django 3.2.8 on 2021-11-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('user', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
