# Generated by Django 3.2.9 on 2021-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='url',
            field=models.URLField(),
        ),
    ]
