# Generated by Django 3.2.8 on 2021-11-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryItem',
        ),
    ]
