# Generated by Django 3.2.8 on 2021-11-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
